/*
 * MenuPpal.java
 *
 * Created on 14 de enero de 2008, 10:35
 */

package vista;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;

import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

import controlador.EscuchaEventos;
import controlador.Eventos;




@SuppressWarnings("all")
public class MenuPpal extends javax.swing.JFrame {
    
	static MenuPpal menu = null;
	SeleccionaClienteFacturar scf = null;
	SeleccionarClienteEditar sce = null;
	SeleccionarFacturaEditar sfe = null;
	
	 public static void main(String args[]) {
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	            	/*creo una instancia pública de eventos*/
	            	
	               
	            	menu = new MenuPpal();
	            	menu.setContentPane(new Contenedor());
	            	menu.setVisible(true);
	            	
	            	
	            }
	        });
	    }
	    
	
	
	private static class Contenedor extends Container
	{
	// La imagen que queremos de fondo, un fichero .gif
	public ImageIcon icono = new ImageIcon ("\\imagenes\\pagppal.jpg");
	

	// Redefinición del método paint()
	public void paint (Graphics g)
	{
	// Borramos todo y lo pintamos del color de fondo por defecto.
	Rectangle r = g.getClipBounds();
	int a = 127;
	int b = 133;
	int c = 249;
	g.setColor(new Color (a, b, c));
	g.fillRect (r.x, r.y, r.width, r.height);

	// Pintamos la imagen
	g.drawImage (icono.getImage(), 25,12,this);

	// Hacemos que se pinten los botones dentro de este contenedor
	super.paint(g);
	}
	}	
	
    public MenuPpal() {
    	
        initComponents();
    }
    
    
    public static void cerraBuscarCliente ()
    {
    	vBuscaCli.setVisible(false);
    }
    
    /*public static JComponent obtenerComponente (String componente)
    {
    	if (componente.compareTo("vFormInsCli")==0) return JComponentvFormInsCli;
    	return null;
    }*/
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jMenuBar1 = new javax.swing.JMenuBar();
        Clientes = new javax.swing.JMenu();
        crearCliente = new javax.swing.JMenuItem();
        reaperturaCliente = new javax.swing.JMenuItem();
        Facturas = new javax.swing.JMenu();
        crearFactura = new javax.swing.JMenuItem();
        reaperturaFactura = new javax.swing.JMenuItem();
        ListadoFacturas = new javax.swing.JMenu();
        resumen = new javax.swing.JMenu();
        primerTrimestre = new javax.swing.JMenuItem();
        primerTrimestre.setName(Eventos.listarFacturasPrimerTrim);
        primerTrimestre.addMouseListener(EscuchaEventos.getInstanceEscuchaEventos());
        
        segundoTrimestre = new javax.swing.JMenuItem();
        segundoTrimestre.setName(Eventos.listarFacturasSegundoTrim);
        segundoTrimestre.addMouseListener(EscuchaEventos.getInstanceEscuchaEventos());
        
        tercerTrimestre = new javax.swing.JMenuItem();
        tercerTrimestre.setName(Eventos.listarFacturasTercerTrim);
        tercerTrimestre.addMouseListener(EscuchaEventos.getInstanceEscuchaEventos());
        
        cuartoTrimestre = new javax.swing.JMenuItem();
        cuartoTrimestre.setName(Eventos.listarFacturasCuartoTrim);
        cuartoTrimestre.addMouseListener(EscuchaEventos.getInstanceEscuchaEventos());
        
        ordinario = new javax.swing.JMenu();
        resumenporfecha = new javax.swing.JMenuItem();
        resumenpornumero = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EUROMORADA - Gestión de clientes y facturas -");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(6);
        setFont(new java.awt.Font("Arial", 0, 20));
        ImageIcon imagen = new ImageIcon ("C:\\imagenes\\logo.jpg");
        Image i = imagen.getImage();
        setIconImage(i);
        ImageIcon fondoVentana = new ImageIcon ("C:\\imagenes\\pagppal.jpg");
        JLabel auxfondo = new JLabel (fondoVentana);
        
        
        //i = imagen.getImage();
        
        
        setName("ventanaPpal");
        setState(6);
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 14));
        Clientes.setText("Clientes");
        Clientes.setFont(new java.awt.Font("Tahoma", 0, 14));
        Clientes.setMargin(new java.awt.Insets(2, 20, 2, 20));
        crearCliente.setFont(new java.awt.Font("Tahoma", 0, 14));
        crearCliente.setText("Crear Cliente");
        crearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearCliente(evt);
            }
        });

        Clientes.add(crearCliente);

        reaperturaCliente.setFont(new java.awt.Font("Tahoma", 0, 14));
        reaperturaCliente.setText("Reapertura Cliente");
        reaperturaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reaperturaCliente(evt);
            }
        });

        Clientes.add(reaperturaCliente);

        jMenuBar1.add(Clientes);

        Facturas.setText("Facturas");
        Facturas.setFont(new java.awt.Font("Tahoma", 0, 14));
        Facturas.setMargin(new java.awt.Insets(2, 20, 2, 20));
        crearFactura.setFont(new java.awt.Font("Tahoma", 0, 14));
        crearFactura.setText("Crear Factura");
        crearFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearFactura(evt);
            }
        });

        Facturas.add(crearFactura);

        reaperturaFactura.setFont(new java.awt.Font("Tahoma", 0, 14));
        reaperturaFactura.setText("Reapertura Factura");
        reaperturaFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reaperturaFactura(evt);
            }
        });

        Facturas.add(reaperturaFactura);

        ListadoFacturas.setText("Listado");
        ListadoFacturas.setFont(new java.awt.Font("Tahoma", 0, 14));
        resumen.setText("Resumen");
        resumen.setFont(new java.awt.Font("Tahoma", 0, 14));
        primerTrimestre.setFont(new java.awt.Font("Tahoma", 0, 14));
        primerTrimestre.setText("1er trimestre");
        resumen.add(primerTrimestre);
        primerTrimestre.setName(Eventos.listarFacturasPrimerTrim);

        segundoTrimestre.setFont(new java.awt.Font("Tahoma", 0, 14));
        segundoTrimestre.setText("2\u00ba trimestre");
        resumen.add(segundoTrimestre);
        segundoTrimestre.setName(Eventos.listarFacturasSegundoTrim);

        tercerTrimestre.setFont(new java.awt.Font("Tahoma", 0, 14));
        tercerTrimestre.setText("3er trimestre");
        resumen.add(tercerTrimestre);
        tercerTrimestre.setName(Eventos.listarFacturasTercerTrim);

        cuartoTrimestre.setFont(new java.awt.Font("Tahoma", 0, 14));
        cuartoTrimestre.setText("4\u00ba trimestre");
        resumen.add(cuartoTrimestre);
        cuartoTrimestre.setName(Eventos.listarFacturasCuartoTrim);

        ListadoFacturas.add(resumen);

        ordinario.setText("Ordinario");
        ordinario.setFont(new java.awt.Font("Tahoma", 0, 14));
        resumenporfecha.setFont(new java.awt.Font("Tahoma", 0, 14));
        resumenporfecha.setText("Por Fecha");
        resumenporfecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                obtenerResumenPorFecha(evt);
            }
        });

        ordinario.add(resumenporfecha);

        resumenpornumero.setFont(new java.awt.Font("Tahoma", 0, 14));
        resumenpornumero.setText("Por N\u00famero");
        resumenpornumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resumenPorNum(evt);
            }
        });

        ordinario.add(resumenpornumero);

        ListadoFacturas.add(ordinario);

        Facturas.add(ListadoFacturas);

        jMenuBar1.add(Facturas);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 281, Short.MAX_VALUE)
        );
        //setContentPane(new Container (auxfondo));
        //pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obtenerResumenPorFecha(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obtenerResumenPorFecha
// TODO add your handling code here:
           new ObtenerListadoFacturaFecha (this, true).setVisible(true);
    }//GEN-LAST:event_obtenerResumenPorFecha

    private void resumenPorNum(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resumenPorNum
// TODO add your handling code here:
           new ObtenerListadoFacturaNumero (this, true).setVisible(true);
    }//GEN-LAST:event_resumenPorNum

    private void reaperturaFactura(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reaperturaFactura
// TODO add your handling code here:
           sfe = SeleccionarFacturaEditar.getInstance();
           if (sfe != null)
           {
        	   sfe.setVisible(true);
           }else MensajesDeInfo.informar (MenuPpal.getMenu(), MensajesDeInfo.sinFacturas);
    }//GEN-LAST:event_reaperturaFactura

    private void crearFactura(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearFactura
// TODO add your handling code here:
    	
    	scf = SeleccionaClienteFacturar.getInstance();
    	if (scf != null)
    		scf.setVisible(true);
    	else MensajesDeInfo.informar (MenuPpal.getMenu(), MensajesDeInfo.sinClientes);
        //new FormularioInsFactura (this, true).setVisible(true);
    }//GEN-LAST:event_crearFactura

    private void reaperturaCliente(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reaperturaCliente
// TODO add your handling code here:
    	SeleccionarClienteEditar bcli = SeleccionarClienteEditar.getInstance();
    	if (bcli !=null)
    	{
    		bcli.setVisible(true);
    	} else MensajesDeInfo.informar (MenuPpal.getMenu(), MensajesDeInfo.sinClientes);
    	
    }//GEN-LAST:event_reaperturaCliente

    private void crearCliente(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearCliente
// TODO add your handling code here:
    	FormularioInsCliente fins = FormularioInsCliente.getInstance();
    	fins.limpiarVentana();
    	fins.visibilizar(true);
    	
    }//GEN-LAST:event_crearCliente
    
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenu Facturas;
    private javax.swing.JMenu ListadoFacturas;
    private javax.swing.JMenuItem crearCliente;
    private javax.swing.JMenuItem crearFactura;
    private javax.swing.JMenuItem cuartoTrimestre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu ordinario;
    private javax.swing.JMenuItem primerTrimestre;
    private javax.swing.JMenuItem reaperturaCliente;
    private javax.swing.JMenuItem reaperturaFactura;
    private javax.swing.JMenu resumen;
    private javax.swing.JMenuItem resumenporfecha;
    private javax.swing.JMenuItem resumenpornumero;
    private javax.swing.JMenuItem segundoTrimestre;
    private javax.swing.JMenuItem tercerTrimestre;
    public static SeleccionarClienteEditar vBuscaCli;
    public static FormularioInsCliente vFormInsCli;
    // End of variables declaration//GEN-END:variables
	public static MenuPpal getMenu() {
		return menu;
	}


	public static void setMenu(MenuPpal menu) {
		MenuPpal.menu = menu;
	}
    
}
