
package vista;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.naming.LimitExceededException;
import javax.swing.DefaultComboBoxModel;

import modelo.Cliente;

import org.jdesktop.layout.*;

import controlador.EscuchaEventos;
import controlador.Eventos;

@SuppressWarnings("all")
public class SeleccionaClienteFacturar extends javax.swing.JDialog {
    
	
	private static SeleccionaClienteFacturar bcli = new SeleccionaClienteFacturar (new MenuPpal (), true);
	
	public static SeleccionaClienteFacturar getInstance ()
	{
		SeleccionaClienteFacturar baux = bcli;
		try
		{
			campoDni.setModel(new DefaultComboBoxModel(Cliente.RecuperarListadoNIFs()));
			elementoSeleccionado = campoDni.getItemAt(0).toString();
		}
		catch (Exception e)
		{
			baux = null;
		} 
		
		return baux;
	}
	
	/*private void limpiarVentana ()
	{
		campoDni.removeAll(); 
	}
	*/
	public void visibilizar (boolean visible)
	{
		this.setVisible(visible);
		//if (!visible) limpiarVentana (); //si se deja de visualzar la ventana, se limpia el contenido del cuadro de texto
			
	}
    /** Creates new form SeleccionaCliente */
    private SeleccionaClienteFacturar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        	
    }
    
    public static String obtenerClienteSeleccionado ()
    {
    	return ((String)campoDni.getSelectedItem());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        
    	setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creación de factura");
    	
    	jPanel16 = new javax.swing.JPanel();
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true), "Datos Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)));
        jPanel16.setFont(new java.awt.Font("Tahoma", 0, 12));
        
        //Vector <String> listaDnis = Cliente.RecuperarListadoNIFs(); 
        
        campoDni = new javax.swing.JComboBox();
        campoDni.setFont(new Font ("Tahoma", 0, 12));
        campoDni.setName(Eventos.clickComboFactCli);
        campoDni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        campoDni.addActionListener(EscuchaEventos.getInstanceEscuchaEventos());
        
        jLabel22 = new javax.swing.JLabel();
        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("DNI/CIF");
        jLabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));
        
        aceptarCliente = new javax.swing.JButton();
        aceptarCliente.setText("Ok");
        aceptarCliente.setName(Eventos.crearFacturaCliente);
        aceptarCliente.addMouseListener(EscuchaEventos.getInstanceEscuchaEventos());
        
        
        


        org.jdesktop.layout.GroupLayout jPanel16Layout = new org.jdesktop.layout.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel16Layout.createSequentialGroup()
                .add(68, 68, 68) 
                .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(campoDni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel22)
                    .add(campoDni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(aceptarCliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(aceptarCliente)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
        
        
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarCliente;
    private static javax.swing.JComboBox campoDni;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel16;
    
    // End of variables declaration//GEN-END:variables
    
    private static String elementoSeleccionado;

	public static String getElementoSeleccionado() {
		return elementoSeleccionado;
	}

	public static void setElementoSeleccionado(String elemento) {
		elementoSeleccionado = elemento;
	}
    
}

