package vista;

import java.awt.Font;

import javax.swing.DefaultComboBoxModel;

import modelo.Cliente;
import modelo.Factura;
import controlador.EscuchaEventos;
import controlador.Eventos;

@SuppressWarnings("all")
public class SeleccionarFacturaEditar extends javax.swing.JDialog  {
	
	
private static SeleccionarFacturaEditar bcli = new SeleccionarFacturaEditar (new MenuPpal (), true);
	
	


	public static SeleccionarFacturaEditar getInstance ()
	{
		SeleccionarFacturaEditar baux = bcli;
		//bcli = new SeleccionarFacturaEditar (new MenuPpal (), true);
		try 
			{
			campoFactura.setModel(new DefaultComboBoxModel(Factura.RecuperarListadoFacturas()));
			elementoSeleccionado = campoFactura.getItemAt(0).toString();
		}
		catch (Exception e) {
			baux = null;
			
		}
		
			
		
		return baux;
	}
	
	
	public void visibilizar (boolean visible)
	{
		this.setVisible(visible);
		//if (!visible) limpiarVentana (); //si se deja de visualzar la ventana, se limpia el contenido del cuadro de texto
			
	}
    /** Creates new form SeleccionaCliente */
    private SeleccionarFacturaEditar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public static String obtenerClienteSeleccionado ()
    {
    	return ((String)campoFactura.getSelectedItem());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        
    	setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reapertura de factura");
    	
    	jPanel16 = new javax.swing.JPanel();
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true), "Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)));
        jPanel16.setFont(new java.awt.Font("Tahoma", 0, 12));
        
        campoFactura = new javax.swing.JComboBox();
        campoFactura.setFont(new Font ("Tahoma", 0, 12));
        campoFactura.setName(Eventos.clickComboFactEdit);
        campoFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        campoFactura.addActionListener(EscuchaEventos.getInstanceEscuchaEventos());
        
        jLabel22 = new javax.swing.JLabel();
        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Nº Factura");
        jLabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));
        
        aceptarFactura = new javax.swing.JButton();
        aceptarFactura.setText("Ok");
        aceptarFactura.setName(Eventos.buscarReaperturaFactura);
        aceptarFactura.addMouseListener(EscuchaEventos.getInstanceEscuchaEventos());
        
        
        


        org.jdesktop.layout.GroupLayout jPanel16Layout = new org.jdesktop.layout.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel16Layout.createSequentialGroup()
                .add(68, 68, 68) 
                .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(campoFactura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel22)
                    .add(campoFactura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(aceptarFactura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(aceptarFactura)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarFactura;
    private static javax.swing.JComboBox campoFactura;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel16;

    private static String elementoSeleccionado;

	public static String getElementoSeleccionado() {
		return elementoSeleccionado;
	}

	public static void setElementoSeleccionado(String elemento) {
		elementoSeleccionado = elemento;
	}
    
    // End of variables declaration//GEN-END:variables


}
